### ISSUE TITLE
Create table view for displaying data

### ISSUE THREAD

**Issue by AdamJonsson** [DM2518-TakeCare/TakeCare#2]
Props should be an array with titles and an array with data

**Comment by ellaklara** [comment]
This should have an editable prop as well.
If it's true you can add and edit items

**Comment by glaufer** [comment]
do we have an example from figma about how it should look like? how many columns/rows/what kind of data it should have? etc

**Comment by ellaklara** [comment]
You should be able to choose number of columns, rows and the headers dynamically with props.
1. On the give help page.
![image](https://user-images.githubusercontent.com/40182097/79785127-a30ff180-8343-11ea-9cae-11fe91311c30.png)
2. On the receive help page.
![image](https://user-images.githubusercontent.com/40182097/79785156-ac995980-8343-11ea-89f2-d33bdf7a6c3d.png)
3. On the create task page.
![image](https://user-images.githubusercontent.com/40182097/79785185-b753ee80-8343-11ea-84ea-59677af495e2.png)
The last one is editable, maybe you could have a prop isEditable that is false by default.

**Comment by AdamJonsson** [comment]
I think the `grid` CSS property can come handy in this issue 😄

**Comment by AdamJonsson** [comment]
The edit functions should be implemented in the component that handles that data, not inside the table. It can be hard to edit items that either are strings or react elements.
