### ISSUE TITLE
Find task page (Map page)

### ISSUE THREAD

**Issue by AdamJonsson** [DM2518-TakeCare/TakeCare#29]
Create a map with markers and content in the bottom slider.
The component that needs to be done in order to complete the page:
* Snapping sheet https://github.com/DM2518-TakeCare/TakeCare/issues/6
* Slider https://github.com/DM2518-TakeCare/TakeCare/issues/3
* Markers https://github.com/DM2518-TakeCare/TakeCare/issues/13
* Table https://github.com/DM2518-TakeCare/TakeCare/issues/2
* Trailing button (Arrow button) https://github.com/DM2518-TakeCare/TakeCare/issues/5

Difficulty level: **5/5**

<img width="290" alt="Screenshot 2020-04-15 at 13 18 59" src="https://user-images.githubusercontent.com/13873828/79331593-b07c4480-7f1b-11ea-82bb-aaf0ed2b0bce.png">

**Comment by glaufer** [comment]
Maybe this can help us?
https://github.com/react-native-community/react-native-maps

**Comment by AdamJonsson** [comment]
@glaufer Nice, will use it 👍

**Comment by AdamJonsson** [comment]
While I was developing this page, the circle and radius control made less sense to have. I believe that It can be a title tedious If the map only shows tasks that are inside the radius. **The user needs to zoom out AND increase the radius to see more tasks**. However, the radius can help the user to get a sense of the distance of the tasks. But this is also shown in the task cards, so I do not believe that the radius is necessary.

Maybe have a type of scrollView that is connected to the markers to make it easier to find the correct marker? Otherwise, the users need to match the number on the marker with the number in the task, this can be hard if there are many markers in a given area.
What do you guys think? @glaufer @ellaklara  @eckernas 
<img src="https://user-images.githubusercontent.com/13873828/79841398-a47b0180-83b7-11ea-9047-7ce912fb1879.gif" width="250px"/>

**Comment by glaufer** [comment]
Considering that you're going to help in your own city/neighbourhood you should have a sense of distance just by looking at the map. is there a way to import the scale, just in case? 

<img width="156" alt="Screenshot 2020-04-21 at 10 16 26" src="https://user-images.githubusercontent.com/57087412/79842530-3df6e300-83b9-11ea-87fa-a5704a879063.png">

Scrollview can help finding the correct marker, but I think that a color change can also do the same effect (by highlighting the current chosen task), like using one of the blues or the coral color.

**Comment by ellaklara** [comment]
I think the scroll view is nice! Just as long as there is an option to center the map again (which it seems there is).
