### ISSUE TITLE
Component for snapping sheet

### ISSUE THREAD

**Issue by ellaklara** [DM2518-TakeCare/TakeCare#6]

**Comment by AdamJonsson** [comment]
Tips: https://github.com/osdnk/react-native-reanimated-bottom-sheet

**Comment by eckernas** [comment]
Nice! Should we just use that one then? Or do you think any changes need to be made? @AdamJonsson

**Comment by AdamJonsson** [comment]
Yea, maybe also create a reusable header component for the bottom sheet?

**Comment by eckernas** [comment]
yeah sounds good! Could you maybe clarify what you mean with the header component?  I saw that in the bottom sheet component there is a prop for the header, so what would my component for the header add to that?

**Comment by AdamJonsson** [comment]
Hmm, what I can think of right now is a "grabbing" component (A grey line that indicates that the sheet is draggable).

**Comment by eckernas** [comment]
ah okay!
