### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by ellaklara** [DM2518-TakeCare/TakeCare#83]

**Comment by glaufer** [comment]
Just say in which format/size and where do you want it :)

![TakeCareIcon](https://user-images.githubusercontent.com/57087412/81294942-e5d60700-906f-11ea-9ec2-ba65bf82a67d.png)

**Comment by glaufer** [comment]
Just say in which format/size and where do you want it :)

![TakeCareIcon2](https://user-images.githubusercontent.com/57087412/81295162-449b8080-9070-11ea-9d10-1fbbca73863b.png)

**Comment by AdamJonsson** [comment]
Nice! Maybe a little more padding around the letters? @glaufer

**Comment by glaufer** [comment]
![TakeCareLogo](https://user-images.githubusercontent.com/57087412/81392408-e9749700-911e-11ea-8c64-003deb1671f3.png)

**Comment by AdamJonsson** [comment]
I like the one with only the T and C

**Comment by glaufer** [comment]
![TakeCareIcon2](https://user-images.githubusercontent.com/57087412/81748530-4c14bc80-94aa-11ea-980c-e205209ef16c.jpg)
